modLoader="javafml"
loaderVersion="[37,)"
license="GPL-3.0 License"
issueTrackerURL="https://github.com/KiwiOfLesbos/Ambrosial/issues"

[[mods]]
modId="ambrosial"
version="1.17.1-1.0.0"
displayName="Ambrosial"
logoFile=""
logoBlue=false
credits="Thanks to all the snails in my backyard."
authors="KiwiOfLesbos"
description="A sweet taste"

[[dependencies.ambrosial]]
modId="forge"
mandatory=true
versionRange="[37,)"
ordering="NONE"
side="BOTH"

[[dependencies.ambrosial]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1,1.18)"
ordering="NONE"
side="BOTH"
