modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
issueTrackerURL="https://github.com/KiwiOfLesbos/Ambrosial/issues"

[[mods]]
modId="ambrosial"
version="1.16.5-0.0.1"
displayName="Ambrosial"
displayURL="https://github.com/KiwiOfLesbos/Ambrosial/"
logoFile="logo.png"
logoBlur=false
credits="Thanks to all the snails in my backyard."
authors="KiwiOfLesbos"
description="Bringing ideas and compatibility to the modpack Ambrosial Skies."
itemIcon="minecraft:obsidian"

[[dependencies.ambrosial]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ambrosial]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ambrosial]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[3.2.0,)"
    ordering="AFTER"
    side="BOTH"