modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/KiwiOfLesbos/Ambrosial/issues"

[[mods]]
modId="ambrosial"
version="0.1.0.0"
displayName="Ambrosial"
itemIcon="minecraft:cooked_beef"
credits="Thanks to all the snails in my backyard."
authors="KiwiOfLesbos"
description="Nothing but cozy vibes."

[[dependencies.ambrosial]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ambrosial]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
