@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package kiwi.ambrosial.blocks;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;